#!/usr/bin/env python3
"""Build real Telangana administrative-boundary fixtures (SRS §20.7, §24.4).

Replaces the simplified placeholder boundaries in ``datasets/telangana/`` with
**authoritative, current** Survey of India boundaries, reshaped into the exact
GeoJSON the existing seed (``scripts/seed_telangana.py``) expects. No application
code changes — boundaries are configuration/data, swapped through the same
ingestion path (SRS §20.7, §21.3).

Source
------
Survey of India administrative boundaries, redistributed as cleaned GeoParquet
(EPSG:4326) by the ``ramSeraph/indian_admin_boundaries`` project, which derives
geometry from official SoI/LGD layers:

    states/SOI_States.parquet, districts/SOI_Districts.parquet,
    subdistricts/SOI_Subdistricts.parquet

Telangana is selected by LGD state code **36** (districts) / state code
``TELANGANA`` (subdistricts). This yields the **current 33-district / mandal**
structure (post-2016 reorganization) — the placeholder fixtures and Census-2011
maps do not.

What it produces (in ``datasets/telangana/``)
---------------------------------------------
- ``state.geojson``         — Telangana outline (union of its districts)
- ``districts.geojson``     — 33 districts   ``{name, code, state}``        [SoI]
- ``mandals.geojson``       — mandals/tehsils ``{name, code, district}``    [SoI]
- ``municipalities.geojson``— ULBs ``{name, district}``: 55 SBM/MoHUA ULBs +
  GHMC (dissolved from its wards); each ULB linked to its district by spatial
  containment, not fragile name matching.                                  [SBM/GHMC]
- ``wards.geojson``         — GHMC wards ``{name, municipality}`` (OpenCity).  [GHMC]
- ``villages.geojson``      — SoI village polygons ``{name, mandal}``, each linked
  to its mandal by spatial containment. Large (~10k features); git-ignored and
  regenerated by this script rather than committed.                          [SoI]

Names are normalized (diacritics stripped, title-cased) so ``state.name`` matches
the State Registry ("Telangana") and the seed's parent-name links resolve.
Geometries are validity-repaired (and forced to 2D) so the seed's checks pass.

Requirements: ``ogr2ogr`` (GDAL with the Parquet driver) on PATH, and ``shapely``
(already a backend dependency). Run from the repo root:

    python scripts/fetch_telangana_admin.py            # download + build
    python scripts/fetch_telangana_admin.py --cache-dir /path/to/parquets
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import unicodedata
from collections import Counter
from pathlib import Path
from typing import Any

from shapely import STRtree, force_2d
from shapely.geometry import MultiPolygon, mapping, shape
from shapely.geometry.base import BaseGeometry
from shapely.ops import unary_union
from shapely.prepared import PreparedGeometry, prep
from shapely.validation import make_valid

_REPO_ROOT = Path(__file__).resolve().parents[1]
_SEED_DIR = _REPO_ROOT / "datasets" / "telangana"
_DEFAULT_CACHE = _REPO_ROOT / "datasets" / "_cache"

_BASE = "https://github.com/ramSeraph/indian_admin_boundaries/releases/download"
_OPENCITY = (
    "https://data.opencity.in/dataset/15cb7d8d-eed1-4aad-8cd7-f281cbf4f94f/resource"
)
_SOURCES = {
    # Survey of India rural hierarchy (state / district / mandal).
    "SOI_Districts.parquet": f"{_BASE}/districts/SOI_Districts.parquet",
    "SOI_Subdistricts.parquet": f"{_BASE}/subdistricts/SOI_Subdistricts.parquet",
    # Urban local bodies (Swachh Bharat Mission / MoHUA) — 55 Telangana ULBs.
    "SBM_ULBs.parquet": f"{_BASE}/urban/SBM_ULBs.parquet",
    # GHMC (Greater Hyderabad) wards — official ward maps via OpenCity (KML).
    "ghmc_wards.kml": f"{_OPENCITY}/14b033e3-3721-4149-8326-cc29420e062e/download/ghmc_wards.kml",
    # Survey of India village polygons (~0.7 GB, all-India) — filtered to Telangana.
    "SOI_villages.parquet": f"{_BASE}/villages/SOI_villages.parquet",
}

# Provenance recorded alongside the generated fixtures.
_PROVENANCE = {
    "rural_hierarchy": {
        "dataset": "Survey of India Administrative Boundaries",
        "source": "ramSeraph/indian_admin_boundaries (SoI/LGD-derived GeoParquet, EPSG:4326)",
        "source_url": "https://github.com/ramSeraph/indian_admin_boundaries",
        "selection": "Telangana — LGD state code 36 (current 33-district structure)",
    },
    "urban_local_bodies": {
        "dataset": "Swachh Bharat Mission ULB boundaries (MoHUA)",
        "source": "ramSeraph/indian_admin_boundaries — urban/SBM_ULBs",
        "selection": "Telangana (stnm='Telangana'); district assigned by spatial containment",
    },
    "wards": {
        "dataset": "GHMC ward boundaries (2022)",
        "source": "Greater Hyderabad Municipal Corporation via OpenCity",
        "source_url": "https://data.opencity.in/dataset/hyderabad-wards-info",
        "selection": "All GHMC wards; parent ULB = Greater Hyderabad Municipal Corporation",
    },
    "villages": {
        "dataset": "Survey of India village boundaries",
        "source": "ramSeraph/indian_admin_boundaries — villages/SOI_villages",
        "selection": "Telangana (STATE_C='TELANGANA'); mandal assigned by spatial containment",
    },
}

_TELANGANA_LGD = 36
_TELANGANA_STATE_C = "TELANGANA"
_GHMC_NAME = "Greater Hyderabad Municipal Corporation"


def _short_code(value: Any) -> str | None:
    """Return a short code string (≤16 chars) or None.

    The SoI ``*_C`` columns hold names rather than short codes; the ``*_L``
    columns hold LGD codes. We keep a value only if it fits the schema's
    ``code`` column (VARCHAR(16)), else store nothing rather than overflow.
    """
    if isinstance(value, str) and 0 < len(value) <= 16:
        return value
    if isinstance(value, int):
        return str(value)
    return None


def _normalize_name(raw: str) -> str:
    """Strip diacritics and title-case a SoI name ('TELANGĀNA' → 'Telangana')."""
    decomposed = unicodedata.normalize("NFKD", raw)
    ascii_only = "".join(c for c in decomposed if not unicodedata.combining(c))
    return " ".join(ascii_only.split()).title()


def _village_name(props: dict[str, Any]) -> str | None:
    """Pick a village's name from whichever attribute the SoI layer uses.

    The SoI village layer's reliably-populated column is ``VILLAGE``; the others
    (``VILL_ROMAN``/``SOI_NAME``/``VT_NAME``) are present but often empty.
    """
    for key in ("VILLAGE", "VILL_ROMAN", "SOI_NAME", "VT_NAME", "Vill_name_2", "Name"):
        value = props.get(key)
        if isinstance(value, str) and value.strip():
            return _normalize_name(value)
    return None


def _download(cache_dir: Path) -> None:
    cache_dir.mkdir(parents=True, exist_ok=True)
    for name, url in _SOURCES.items():
        dest = cache_dir / name
        if dest.exists() and dest.stat().st_size > 0:
            print(f"  cached  {name} ({dest.stat().st_size / 1e6:.1f} MB)")
            continue
        print(f"  fetch   {name} …")
        subprocess.run(
            ["curl", "-sSL", "--fail", "-o", str(dest), url], check=True, timeout=600
        )


def _ogr_features(
    path: Path, layer: str, where: str | None = None
) -> list[dict[str, Any]]:
    """Run ogr2ogr to dump (optionally filtered) features as GeoJSON, EPSG:4326."""
    cmd = ["ogr2ogr", "-f", "GeoJSON", "-t_srs", "EPSG:4326"]
    if where is not None:
        cmd += ["-where", where]
    cmd += ["/vsistdout/", str(path), layer]
    out = subprocess.run(cmd, check=True, capture_output=True, timeout=600)
    return json.loads(out.stdout)["features"]


def _polygonal_multipolygon(geom: BaseGeometry) -> MultiPolygon:
    """Coerce any geometry to a MultiPolygon of its polygonal parts only.

    Validity repair (``make_valid``) and unioning can emit GeometryCollections
    that mix polygons with stray slivers (lines/points); the ``MULTIPOLYGON``
    columns reject those. We keep the polygons and drop the rest.
    """
    parts: list[BaseGeometry] = []

    def _collect(g: BaseGeometry) -> None:
        if g.is_empty:
            return
        if g.geom_type == "Polygon":
            parts.append(g)
        elif g.geom_type == "MultiPolygon":
            parts.extend(g.geoms)
        elif g.geom_type == "GeometryCollection":
            for sub in g.geoms:
                _collect(sub)
        # lines/points from repair are intentionally discarded

    _collect(geom)
    if not parts:
        raise ValueError("geometry has no polygonal component after repair")
    return MultiPolygon(parts)


def _clean_geom(geojson_geom: dict[str, Any]) -> MultiPolygon:
    """Parse + validity-repair a geometry as a clean 2D MultiPolygon (seed-ready)."""
    geom = force_2d(shape(geojson_geom))  # KML carries Z; columns are 2D
    if not geom.is_valid:
        geom = make_valid(geom)
    return _polygonal_multipolygon(geom)


def _assign_parent(
    geom: BaseGeometry, parents: list[tuple[str, PreparedGeometry]]
) -> str | None:
    """Name of the parent polygon containing ``geom``'s representative point.

    Used to link a ULB to its district (and a ward to its ULB) by spatial
    containment rather than fragile cross-source name matching.
    """
    point = geom.representative_point()
    for name, prepared in parents:
        if prepared.contains(point):
            return name
    return None


def _feature(geom: BaseGeometry, properties: dict[str, Any]) -> dict[str, Any]:
    return {"type": "Feature", "properties": properties, "geometry": mapping(geom)}


def _write(name: str, features: list[dict[str, Any]]) -> None:
    path = _SEED_DIR / f"{name}.geojson"
    payload = {"type": "FeatureCollection", "features": features}
    path.write_text(json.dumps(payload), encoding="utf-8")
    print(
        f"  wrote   {name}.geojson  ({len(features)} features, {path.stat().st_size / 1e6:.2f} MB)"
    )


def build(cache_dir: Path) -> None:
    print("Downloading authoritative boundaries (Survey of India via ramSeraph)…")
    _download(cache_dir)

    # --- Districts (current 33) ------------------------------------------- #
    print("Building districts…")
    district_features: list[dict[str, Any]] = []
    district_geoms: list[BaseGeometry] = []
    district_names: set[str] = set()
    for feat in _ogr_features(
        cache_dir / "SOI_Districts.parquet",
        "SOI_Districts",
        f"State_LGD={_TELANGANA_LGD}",
    ):
        props = feat["properties"]
        name = _normalize_name(props["District"])
        geom = _clean_geom(feat["geometry"])
        district_names.add(name)
        district_geoms.append(geom)
        district_features.append(
            _feature(
                geom,
                {
                    "name": name,
                    "code": _short_code(props.get("DISTRICT_L")),
                    "state": "Telangana",
                },
            )
        )

    # --- State (union of districts → one consistent outline) -------------- #
    print("Dissolving state outline…")
    state_geom = _polygonal_multipolygon(unary_union(district_geoms))
    state_features = [_feature(state_geom, {"name": "Telangana", "code": "TG"})]

    # --- Mandals (subdistricts, linked to districts by name) -------------- #
    print("Building mandals…")
    mandal_features: list[dict[str, Any]] = []
    mandal_geoms: list[BaseGeometry] = []
    dropped = 0
    for feat in _ogr_features(
        cache_dir / "SOI_Subdistricts.parquet",
        "SOI_Subdistricts",
        f"STATE_C='{_TELANGANA_STATE_C}'",
    ):
        props = feat["properties"]
        district = _normalize_name(props["District"])
        if district not in district_names:
            dropped += 1  # mandal whose parent district didn't resolve — skip
            continue
        geom = _clean_geom(feat["geometry"])
        mandal_geoms.append(geom)
        mandal_features.append(
            _feature(
                geom,
                {
                    "name": _normalize_name(props["TEHSIL"]),
                    "code": _short_code(props.get("TEHSIL_C")),
                    "district": district,
                },
            )
        )
    if dropped:
        print(f"  note    skipped {dropped} mandals with no matching district")

    # Disambiguate duplicate mandal names (e.g. two 'Kothapalli' in different
    # districts) so village→mandal links — keyed by mandal name in the seed — are
    # unambiguous and villages resolve under the correct mandal.
    name_counts = Counter(f["properties"]["name"] for f in mandal_features)
    for feat in mandal_features:
        nm = feat["properties"]["name"]
        if name_counts[nm] > 1:
            feat["properties"]["name"] = f"{nm} ({feat['properties']['district']})"
    mandal_names = [f["properties"]["name"] for f in mandal_features]

    # Prepared district polygons for spatial parent assignment (ULB → district).
    district_index = [
        (f["properties"]["name"], prep(shape(f["geometry"]))) for f in district_features
    ]

    # --- Municipalities: SBM ULBs (55) + GHMC (dissolved from its wards) --- #
    print("Building municipalities (ULBs)…")
    muni_features: list[dict[str, Any]] = []
    unplaced = 0
    for feat in _ogr_features(
        cache_dir / "SBM_ULBs.parquet", "SBM_ULBs", "stnm='Telangana'"
    ):
        geom = _clean_geom(feat["geometry"])
        district = _assign_parent(geom, district_index)
        if district is None:
            unplaced += 1  # ULB centroid outside every district polygon — skip
            continue
        name = _normalize_name(feat["properties"]["ulbnm"])
        muni_features.append(_feature(geom, {"name": name, "district": district}))
    if unplaced:
        print(f"  note    skipped {unplaced} ULBs with no containing district")

    # GHMC wards (OpenCity) — dissolve into the GHMC municipality polygon.
    print("Building wards (GHMC)…")
    ghmc_ward_features = _ogr_features(cache_dir / "ghmc_wards.kml", "wards")
    ghmc_ward_geoms = [_clean_geom(f["geometry"]) for f in ghmc_ward_features]
    ghmc_geom = _polygonal_multipolygon(unary_union(ghmc_ward_geoms))
    ghmc_district = _assign_parent(ghmc_geom, district_index) or "Hyderabad"
    muni_features.append(
        _feature(ghmc_geom, {"name": _GHMC_NAME, "district": ghmc_district})
    )

    ward_features = [
        _feature(
            geom,
            {
                "name": _normalize_name(f["properties"]["ward"]),
                "municipality": _GHMC_NAME,
            },
        )
        for f, geom in zip(ghmc_ward_features, ghmc_ward_geoms)
    ]

    # --- Villages (SOI, linked to mandals by spatial containment) --------- #
    print("Building villages (large source — this step takes longest)…")
    mandal_tree = STRtree(mandal_geoms)
    village_features: list[dict[str, Any]] = []
    v_dropped = 0
    for feat in _ogr_features(
        cache_dir / "SOI_villages.parquet",
        "SOI_villages",
        f"STATE_C='{_TELANGANA_STATE_C}'",
    ):
        name = _village_name(feat["properties"])
        if name is None:
            v_dropped += 1
            continue
        geom = _clean_geom(feat["geometry"])
        point = geom.representative_point()
        mandal_idx = next(
            (
                int(i)
                for i in mandal_tree.query(point)
                if mandal_geoms[int(i)].contains(point)
            ),
            None,
        )
        if mandal_idx is None:
            v_dropped += 1  # village outside every mandal polygon — skip
            continue
        village_features.append(
            _feature(geom, {"name": name, "mandal": mandal_names[mandal_idx]})
        )
    if v_dropped:
        print(
            f"  note    skipped {v_dropped} villages with no name or containing mandal"
        )

    # --- Write fixtures --------------------------------------------------- #
    print(f"Writing fixtures to {_SEED_DIR}…")
    _write("state", state_features)
    _write("districts", district_features)
    _write("mandals", mandal_features)
    _write("municipalities", muni_features)
    _write("wards", ward_features)
    _write("villages", village_features)

    (_SEED_DIR / "ADMIN_PROVENANCE.json").write_text(
        json.dumps(
            {
                **_PROVENANCE,
                "counts": {
                    "state": len(state_features),
                    "districts": len(district_features),
                    "mandals": len(mandal_features),
                    "municipalities": len(muni_features),
                    "wards": len(ward_features),
                    "villages": len(village_features),
                },
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    print(
        f"Done. {len(district_features)} districts, {len(mandal_features)} mandals, "
        f"{len(muni_features)} municipalities, {len(ward_features)} GHMC wards, "
        f"{len(village_features)} villages."
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--cache-dir",
        type=Path,
        default=_DEFAULT_CACHE,
        help="Where to cache the downloaded GeoParquet source files.",
    )
    args = parser.parse_args()
    try:
        build(args.cache_dir)
    except FileNotFoundError as exc:  # ogr2ogr missing
        print(
            f"error: {exc}. Is GDAL (ogr2ogr) installed and on PATH?", file=sys.stderr
        )
        raise SystemExit(1) from exc


if __name__ == "__main__":
    main()
